name: Build latest
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build-mono:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Survival Client (CS) using mono
        shell: bash
        id: compile
        run: |
          msbuild ClassicalSharp.sln /p:Configuration=Release
          cp -R output/release output/release_peaceful
          rm output/release/ClassicalSharp.exe output/release/SharpWave.dll output/release/Launcher2.exe  output/release/OpenTK.dll
          msbuild ClassicalSharp/ClassicalSharp.csproj /p:Configuration=Release /t:Rebuild /p:DefineConstants="PEACEFUL"
          msbuild InteropPatcher/InteropPatcher.csproj /p:Configuration=Release
          msbuild Launcher2/Launcher2.csproj /p:Configuration=Release 
          msbuild OpenTK/OpenTK.csproj /p:Configuration=Release

      - uses: ./.github/actions/notify_failure_cs
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Survival Client (CS) build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success_cs
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'output/release'
          DEST_NAME: 'Survival'
          NOTIFY_MESSAGE: 'Successfully compiled Survival Client (CS) build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success_cs
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'output/release_peaceful'
          DEST_NAME: 'Survival-Peaceful'
          NOTIFY_MESSAGE: 'Successfully compiled Survival Client (CS) Peaceful build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'